from tomcat:8.5.35

RUN echo 'export CATALINA_OPTS="$CATALINA_OPTS -Dmysql.host=${MYSQL_HOST} -Dmysql.port=${MYSQL_PORT}"' >> /usr/local/tomcat/bin/setenv.sh

COPY webapps/Cars_Sample_App.war /usr/local/tomcat/webapps/Cars_Sample_App.war
COPY webapps/context.xml /usr/local/tomcat/conf/context.xml

EXPOSE 8080
CMD ["catalina.sh", "run"]

